# Training Configuration

# --- General Settings ---
seed: 1

# --- Data Settings ---
data_path: "../data" # Relative or absolute path to the data directory
train_parquet_file: "train/segments_train.parquet"
val_parquet_file: "train/segments_val.parquet"
distances_csv_file: "distances_3d.csv"
val_split_size: 0.1 # Proportion of training data to use for validation

# --- Preprocessing Settings ---
signal_processing:
  filtering_type: "frequency_domain"
  bandpass_filter:
    order: 4
    lowcut: 0.5
    highcut: 30.0
    fs: 250

model:
  name: "BiLSTM" 
  num_eeg_channels: 19
  hidden_size: 256
  num_layers: 2
  fc_layers: [256, 64]
  num_classes: 1

# --- Training Hyperparameters ---
training:
  batch_size: 128
  epochs: 200
  lr: 0.0005 # 5e-4
  weight_decay: 0.00001 # 1e-5
  max_norm: 1.0
  pos_weight: True

# --- Checkpoint Settings ---
checkpoint:
  save_dir_in_wandb: true # Saves checkpoints in wandb run directory
  best_model_filename: "best_bilstm_model.pth"
  final_model_filename: "final_bilstm_model.pth" # Note: script uses 'final_dtgcn_model.pth' but refers to SMOTE model

# --- Weights & Biases Logging ---
wandb:
  project: "eeg-DTGCN"
  run_name: "BiLSTM"
  log_gradients: true